name: Build & Test & Pack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build projects
        run: dotnet build --configuration Release --no-restore
      - name: Test projects
        run: dotnet test
      # - name: Pack projects
      #   run: dotnet pack --no-restore
      - name: Upload packages (artifacts)
        uses: actions/upload-artifact@v2
        with:
          name: nuget-packages
          path: |
            src/**/*.nupkg
            src/**/*.snupkg
  publish:
    runs-on: windows-latest
    steps:
      - name: Download packages (artifacts)
        uses: actions/download-artifact@v2
        with:
          name: nuget-packages
          path: |
            src/**/*.nupkg
            src/**/*.snupkg
      - name: Push nupkg's
        id: push-nupkg
        run: echo "::set-output name=CONSOLE::$(dotnet nuget push '**/*.nupkg' --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}})" --skip-duplicate
        continue-on-error: true
      - name: Push nupkg's suceeded
        if: "${{ contains(steps.push-nupkg.outputs.CONSOLE, 'error: File does not exist') }}"
        run: exit 1
      - name: Push snupkg's
        id: push-snupkg
        if: success()
        run: echo "::set-output name=CONSOLE::$(dotnet nuget push '**/*.snupkg' --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}})" --skip-duplicate
        continue-on-error: true
      - name: Push snupkg's suceeded
        if: "${{ contains(steps.push-nupkg.outputs.CONSOLE, 'error: File does not exist') }}"
        run: exit 1
