name: Build & Test & Pack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build projects
        run: dotnet build --configuration Release --no-restore
      - name: Test projects
        run: dotnet test
      - name: Pack projects
        run: dotnet pack --no-restore
      - name: Upload packages (artifacts)
        uses: actions/upload-artifact@v2
        with:
          name: nuget-packages
          path: |
            '**/*.nupkg'
            '**/*.snupkg'

